name: Update Node.js

on:
  schedule:
    - cron: "0 11 * * *"  # Runs daily at 11:00 UTC
  workflow_dispatch:

jobs:
  update:
    uses: mercadona/github-actions/.github/workflows/update-nodejs.yml@4a8afe770a771b51f009cc9d489d3be931229c74 # v1.7.2